# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/jaypipes/ghw"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"
