name: CI tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# see: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
jobs:
  # tier 0: system-independent checks
  format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: set up golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: format
      run: ./hack/check-format.sh

  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Verify
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41.1
        args: --timeout=15m0s --verbose

  # tier-1
  # main development platfotm, gets features first and it's most tested
  build-ubuntu-2004:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.18', '1.19']
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      env:
        GHW_TESTING_SKIP_BLOCK: "1"
        GHW_TESTING_SKIP_GPU: "1"
      run: go test -v ./...

  # tier-2
  # best-effort support, limited to most recent platforms (OS+go)
  build-windows-2019:
    runs-on: windows-2019
    strategy:
      matrix:
        go: [ '1.18' ]
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      env:
        GHW_TESTING_SKIP_BLOCK: "1"
        GHW_TESTING_SKIP_CPU: "1"
        GHW_TESTING_SKIP_GPU: "1"
        GHW_TESTING_SKIP_HOST: "1"
        GHW_TESTING_SKIP_MEMORY: "1"
        GHW_TESTING_SKIP_NET: "1"
        GHW_TESTING_SKIP_PCI: "1"
        GHW_TESTING_SKIP_TOPOLOGY: "1"
      run: go test -v ./...

  # tier-2
  # best-effort support, limited to most recent platforms (OS+go)
  # TODO: check this is the last on x86, the switch to arm is nontrivial
  build-macos-1015:
    runs-on: macos-10.15
    strategy:
      matrix:
        go: [ '1.18' ]
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      env:
        GHW_TESTING_SKIP_BLOCK: "1"
        GHW_TESTING_SKIP_CPU: "1"
        GHW_TESTING_SKIP_GPU: "1"
        GHW_TESTING_SKIP_HOST: "1"
        GHW_TESTING_SKIP_MEMORY: "1"
        GHW_TESTING_SKIP_NET: "1"
        GHW_TESTING_SKIP_PCI: "1"
        GHW_TESTING_SKIP_TOPOLOGY: "1"
      run: go test -v ./...
