name: CI tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# see: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
jobs:
  # tier 0: system-independent checks
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Verify
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.41.1
        args: --timeout=15m0s --verbose

  # tier-1
  # main development platform, gets features first and it's most tested
  build-ubuntu-2204:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: [ '1.19', '1.20']
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      env:
        GHW_TESTING_SKIP_BLOCK: "1"
        GHW_TESTING_SKIP_GPU: "1"
      run: go test -v ./...

  build-ubuntu-2004:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ '1.18', '1.19']
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      env:
        GHW_TESTING_SKIP_BLOCK: "1"
        GHW_TESTING_SKIP_GPU: "1"
      run: go test -v ./...

  build-windows-2022:
    runs-on: windows-2022
    strategy:
      matrix:
        go: [ '1.19' ]
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      env:
        GHW_TESTING_SKIP_BLOCK: "1"
        GHW_TESTING_SKIP_GPU: "1"
        GHW_TESTING_SKIP_CPU: "1"
        GHW_TESTING_SKIP_MEMORY: "1"
        GHW_TESTING_SKIP_HOST: "1"
        GHW_TESTING_SKIP_NET: "1"
        GHW_TESTING_SKIP_PCI: "1"
        GHW_TESTING_SKIP_TOPOLOGY: "1"
      run: go test -v ./...

  build-windows-2019:
    runs-on: windows-2019
    strategy:
      matrix:
        go: [ '1.18' ]
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      env:
        GHW_TESTING_SKIP_BLOCK: "1"
        GHW_TESTING_SKIP_CPU: "1"
        GHW_TESTING_SKIP_GPU: "1"
        GHW_TESTING_SKIP_HOST: "1"
        GHW_TESTING_SKIP_MEMORY: "1"
        GHW_TESTING_SKIP_NET: "1"
        GHW_TESTING_SKIP_PCI: "1"
        GHW_TESTING_SKIP_TOPOLOGY: "1"
      run: go test -v ./...

  # tier-2
  # best-effort support, limited to most recent platforms (OS+go)

  # NOTE(jaypipes): We currently only support block information on MacOS, and
  # the tests have block skipped because we cannot get meaningful information
  # about the block devices in the Github Actions Runner virtual machines. So
  # this is really just a test of whether the library builds on MacOS 12.
  build-macos-12:
    runs-on: macos-12
    strategy:
      matrix:
        go: [ '1.18' ]
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: run unit-tests
      env:
        GHW_TESTING_SKIP_BLOCK: "1"
        GHW_TESTING_SKIP_CPU: "1"
        GHW_TESTING_SKIP_GPU: "1"
        GHW_TESTING_SKIP_HOST: "1"
        GHW_TESTING_SKIP_MEMORY: "1"
        GHW_TESTING_SKIP_NET: "1"
        GHW_TESTING_SKIP_PCI: "1"
        GHW_TESTING_SKIP_TOPOLOGY: "1"
      run: go test -v ./...
