name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: run unit-tests
      env:
        GHW_TESTING_SKIP_BLOCK: "1"
        GHW_TESTING_SKIP_GPU: "1"
      run: go test -v ./...
